export default {
	SNSアイコン: [ 'fab fa-twitter', 'fab fa-facebook-f', 'fab fa-instagram' ],
	'Font Awesome アイコン': [
		'fab fa-accessible-icon',
		'fas fa-ambulance',
		'fas fa-bicycle',
		'fas fa-bus',
		'fas fa-car',
		'fas fa-fighter-jet',
		'fas fa-motorcycle',
		'fas fa-paper-plane',
		'far fa-paper-plane',
		'fas fa-plane',
		'fas fa-rocket',
		'fas fa-ship',
		'fas fa-shopping-cart',
		'fas fa-space-shuttle',
		'fas fa-subway',
		'fas fa-taxi',
		'fas fa-train',
		'fas fa-truck',
		'fas fa-wheelchair',
		'fab fa-accessible-icon',
		'fas fa-ambulance',
		'fas fa-bicycle',
		'fas fa-bus',
		'fas fa-car',
		'fas fa-fighter-jet',
		'fas fa-motorcycle',
		'fas fa-paper-plane',
		'far fa-paper-plane',
		'fas fa-plane',
		'fas fa-rocket',
		'fas fa-ship',
		'fas fa-shopping-cart',
		'fas fa-space-shuttle',
		'fas fa-subway',
		'fas fa-taxi',
		'fas fa-train',
		'fas fa-truck',
		'fas fa-wheelchair',
	],
	// 'SWELL アイコン': [
	//     'icon-checkmark',
	//     'icon-flag',
	//     'icon-phone1',
	//     'icon-markunread',
	//     'icon-shopping_cart',
	//     'icon-person',
	//     'icon-settings',
	//     'icon-download',
	//     'icon-envelope',
	//     'icon-light-bulb',
	//     'icon-lock-closed',
	//     'icon-lock-open',
	//     'icon-book',
	//     'icon-megaphone'
	// ],
};
